---
title: 'BUDA 525: Team 4 Final Project'
author: "Ryan Antonini, Danny Germain, Joshua Meadows, Josh Nelson, Bill Robertson"
date: "9/27/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ISLR)
library(effects)
library(car)
library(doParallel)
library(carData)
```

# Problem 1



# Problem 2



# Problem 3


```{r chunk3_1, echo=FALSE}
#head(Credit)
summary(Credit)
```

```{r chunk3_2,echo=FALSE}
mod3_1 <- lm(Balance~ID+Income+Limit+Rating+Cards+Education+Gender+Student+Married+Ethnicity,data=Credit)
#We start by fitting a model with all predictors to find out how to procede
summary(mod3_1)
```

```{r chunk3_3,echo=FALSE}
mod3_2 <- lm(Balance~ID+Income+Limit+Rating+Cards+Education+Student+Married,data=Credit)
#Next we fit a model without Gender and Ethnicity since we don't want to use them, and compare them to the model with all predictors
#summary(mod3_2)
anova(mod3_1,mod3_2)
```

```{r chunk3_4,echo=FALSE}
mod3_3 <- step(mod3_2)
summary(mod3_3)
anova(mod3_1,mod3_3)
#testing to see what we can drop
```

```{r chunk3_5, echo=FALSE }
ncvTest(mod3_3)
par(mfrow=c(2,2))
plot(mod3_3)
#avPlots(mod3_3)
#plot(allEffects(mod3_3))
#Running Diagnostics
```


```{r chunk3_6, echo=FALSE}
Credit2<- Credit[Credit$Balance!=0,]
mod3_4 <- lm(Balance~Income+Limit+Rating+Cards+Student,data=Credit2)
summary(mod3_4)
```

```{r chunk3_7, echo=FALSE}
ncvTest(mod3_4)
par(mfrow=c(2,2))
plot(mod3_4)
#avPlots(mod3_4)
plot(allEffects(mod3_4))
#Running Diagnostics
```

## Dealing with zero balance

```{r chunk3_8, echo=FALSE}
Credit3<-Credit
Credit3$BalanceF<- as.numeric(Credit3$Balance>0)
mod3_5<- step(lm(BalanceF~Limit+Student+Rating+Cards+Education+Income,data=Credit3))
summary(mod3_5)
```



```{r chunk3_9, echo=FALSE}
mod3_7<-step(lm(BalanceF~Student*Limit*Income,data=Credit3))
```

```{r chunk3_10, echo=FALSE}
mine<-detectCores()
mine<-min(c(max(c(1,mine-1)),5))
cl<-makeCluster(mine)
registerDoParallel(cl)
getDoParWorkers()
library(doRNG)
library(foreach)

foreach(i=1:1000,.combine="+",.options.RNG=623)%dopar% {
  set=sample(1:dim(Credit3)[1],300,replace=FALSE)
	M1<-lm(BalanceF~Student*Limit+Student*Income+Income*Limit,data=Credit3[set,])
	Predict <- predict(M1,newdata=Credit3[-set,])
	myPredict<- ifelse(Predict >0.5,"1","0")
	mytable <- table(Credit3[-set,]$BalanceF,myPredict)
	eff<-sum(diag(mytable))/sum(mytable)
	return(eff)
}

stopCluster(cl)
```



```{r chunk3_11, include=FALSE}
mod3_8<-step(lm(Balance~(Student*Limit*Income)*(log(Rating)+Cards+Student+Limit+Income),data=Credit3))
```

```{r chunk3_12, echo=FALSE}
summary(mod3_8)
ncvTest(mod3_8)
par(mfrow=c(2,2))
plot(mod3_8)
```


# Problem 4

```{r chunk4_1,echo=FALSE}
#head(Salaries)
summary(Salaries)
```

```{r chunk4_2, echo=FALSE}
mod4_1<-lm(salary~rank+discipline+yrs.since.phd+yrs.service+sex, data=Salaries)
summary(mod4_1)
```

